export const mockGenres = [
  { id: 1, name: 'Aksiyon' },
  { id: 2, name: 'Macera' },
  { id: 3, name: 'Animasyon' },
  { id: 4, name: 'Komedi' },
  { id: 5, name: 'Suç' },
  { id: 6, name: 'Belgesel' },
  { id: 7, name: 'Dram' },
  { id: 8, name: 'Aile' },
  { id: 9, name: 'Fantastik' },
  { id: 10, name: 'Tarih' },
  { id: 11, name: 'Korku' },
  { id: 12, name: 'Müzik' },
  { id: 13, name: 'Gizem' },
  { id: 14, name: 'Romantik' },
  { id: 15, name: 'Bilim Kurgu' },
  { id: 16, name: 'TV Filmi' },
  { id: 17, name: 'Gerilim' },
  { id: 18, name: 'Savaş' },
  { id: 19, name: 'Western' },
]

export const mockMovies = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    description: 'İki adam, hapishane duvarlarının ardında dostluk kurar ve yıllar boyunca süren bir bağ oluşturur.',
    poster: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    releaseDate: '1994-09-23',
    rating: 9.3,
    voteCount: 23456,
    genres: [{ id: 7, name: 'Dram' }, { id: 5, name: 'Suç' }],
    runtime: 142,
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
  },
  {
    id: 2,
    title: 'The Godfather',
    description: 'Yaşlanan bir suç patronu, kontrolü isteksiz oğluna devretmeye karar verir.',
    poster: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    releaseDate: '1972-03-24',
    rating: 9.2,
    voteCount: 17890,
    genres: [{ id: 7, name: 'Dram' }, { id: 5, name: 'Suç' }],
    runtime: 175,
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
  },
  {
    id: 3,
    title: 'The Dark Knight',
    description: 'Batman, Gotham halkına kaos getiren Joker olarak bilinen tehditle karşı karşıya gelir.',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    releaseDate: '2008-07-18',
    rating: 9.0,
    voteCount: 29345,
    genres: [{ id: 1, name: 'Aksiyon' }, { id: 5, name: 'Suç' }, { id: 7, name: 'Dram' }],
    runtime: 152,
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
  },
  {
    id: 4,
    title: 'Pulp Fiction',
    description: 'Los Angeles yeraltı dünyasından birbirine bağlı hikayeler.',
    poster: 'https://image.tmdb.org/t/p/w500/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg',
    releaseDate: '1994-10-14',
    rating: 8.9,
    voteCount: 24567,
    genres: [{ id: 5, name: 'Suç' }, { id: 17, name: 'Gerilim' }],
    runtime: 154,
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
  },
  {
    id: 5,
    title: 'Forrest Gump',
    description: 'Düşük IQlu bir adam, 20. yüzyılın önemli olaylarına tanık olur.',
    poster: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxRVY6N9uugaVA.jpg',
    releaseDate: '1994-07-06',
    rating: 8.8,
    voteCount: 23789,
    genres: [{ id: 7, name: 'Dram' }, { id: 14, name: 'Romantik' }],
    runtime: 142,
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
  },
  {
    id: 6,
    title: 'Inception',
    description: 'Bir hırsız, kurumsal casusluk dünyasında rüyalara girme yeteneğine sahiptir.',
    poster: 'https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    releaseDate: '2010-07-16',
    rating: 8.8,
    voteCount: 32456,
    genres: [{ id: 1, name: 'Aksiyon' }, { id: 15, name: 'Bilim Kurgu' }, { id: 17, name: 'Gerilim' }],
    runtime: 148,
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Marion Cotillard', 'Elliot Page'],
  },
  {
    id: 7,
    title: 'The Matrix',
    description: 'Bir bilgisayar programcısı, gerçekliğin simülasyon olduğunu keşfeder.',
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    releaseDate: '1999-03-31',
    rating: 8.7,
    voteCount: 22345,
    genres: [{ id: 1, name: 'Aksiyon' }, { id: 15, name: 'Bilim Kurgu' }],
    runtime: 136,
    director: 'Lana Wachowski, Lilly Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
  },
  {
    id: 8,
    title: 'Interstellar',
    description: 'Bir grup kaşif, insanlığın hayatta kalmasını sağlamak için bir solucan deliğinden geçer.',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    releaseDate: '2014-11-07',
    rating: 8.6,
    voteCount: 29876,
    genres: [{ id: 2, name: 'Macera' }, { id: 7, name: 'Dram' }, { id: 15, name: 'Bilim Kurgu' }],
    runtime: 169,
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
  },
  {
    id: 9,
    title: 'Fight Club',
    description: 'Uykusuz bir ofis çalışanı ve sabun satıcısı yeraltı dövüş kulübü kurar.',
    poster: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    releaseDate: '1999-10-15',
    rating: 8.8,
    voteCount: 25678,
    genres: [{ id: 7, name: 'Dram' }],
    runtime: 139,
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
  },
  {
    id: 10,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    description: 'Hobbit ve arkadaşları, Tek Yüzüğü yok etmek için yola çıkar.',
    poster: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/pIUvQ9Ed35wlWhY2oU6OmwEsmzG.jpg',
    releaseDate: '2001-12-19',
    rating: 8.8,
    voteCount: 22345,
    genres: [{ id: 2, name: 'Macera' }, { id: 9, name: 'Fantastik' }, { id: 1, name: 'Aksiyon' }],
    runtime: 178,
    director: 'Peter Jackson',
    cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
  },
  {
    id: 11,
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    description: 'İsyancılar İmparatorluk güçlerine karşı savaşmaya devam eder.',
    poster: 'https://image.tmdb.org/t/p/w500/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/azIbhk98KmvMpLfBXtKpZ4K8tXL.jpg',
    releaseDate: '1980-05-21',
    rating: 8.7,
    voteCount: 14567,
    genres: [{ id: 2, name: 'Macera' }, { id: 1, name: 'Aksiyon' }, { id: 15, name: 'Bilim Kurgu' }],
    runtime: 124,
    director: 'Irvin Kershner',
    cast: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
  },
  {
    id: 12,
    title: 'Goodfellas',
    description: 'Henry Hill ve arkadaşlarının mafya dünyasında yükselişi ve düşüşü.',
    poster: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/sw7mordbZxgITU877yTpZCud90M.jpg',
    releaseDate: '1990-09-19',
    rating: 8.7,
    voteCount: 10987,
    genres: [{ id: 7, name: 'Dram' }, { id: 5, name: 'Suç' }],
    runtime: 146,
    director: 'Martin Scorsese',
    cast: ['Ray Liotta', 'Robert De Niro', 'Joe Pesci'],
  },
  {
    id: 13,
    title: 'One Flew Over the Cuckoo\'s Nest',
    description: 'Akıl hastanesindeki hasta, tiranlık hemşireye karşı isyan başlatır.',
    poster: 'https://image.tmdb.org/t/p/w500/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/4E7YQcwui0PfNXguf4V2X8YocPC.jpg',
    releaseDate: '1975-11-19',
    rating: 8.7,
    voteCount: 9876,
    genres: [{ id: 7, name: 'Dram' }],
    runtime: 133,
    director: 'Miloš Forman',
    cast: ['Jack Nicholson', 'Louise Fletcher', 'Danny DeVito'],
  },
  {
    id: 14,
    title: 'Se7en',
    description: 'İki dedektif, yedi ölümcül günahı temel alan seri katili yakalar.',
    poster: 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVOO.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/ba4CpvnaxvAgff2jHiaqJrVpZJ5.jpg',
    releaseDate: '1995-09-22',
    rating: 8.6,
    voteCount: 18765,
    genres: [{ id: 5, name: 'Suç' }, { id: 13, name: 'Gizem' }, { id: 17, name: 'Gerilim' }],
    runtime: 127,
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow'],
  },
  {
    id: 15,
    title: 'The Silence of the Lambs',
    description: 'Genç FBI ajanı, seri katili yakalamak için hapisteki psikopattan yardım ister.',
    poster: 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fCvZSgPIKYpk1yWpv8S1KzBe7tE.jpg',
    releaseDate: '1991-02-14',
    rating: 8.6,
    voteCount: 13456,
    genres: [{ id: 5, name: 'Suç' }, { id: 7, name: 'Dram' }, { id: 17, name: 'Gerilim' }],
    runtime: 118,
    director: 'Jonathan Demme',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
  },
  {
    id: 16,
    title: 'Saving Private Ryan',
    description: 'D-Day istilası sırasında, bir grup asker kayıp askeri bulmak için görevlendirilir.',
    poster: 'https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hjQp148VjWF4KjzhsD90OCMr11h.jpg',
    releaseDate: '1998-07-24',
    rating: 8.6,
    voteCount: 13234,
    genres: [{ id: 7, name: 'Dram' }, { id: 10, name: 'Tarih' }, { id: 18, name: 'Savaş' }],
    runtime: 169,
    director: 'Steven Spielberg',
    cast: ['Tom Hanks', 'Matt Damon', 'Tom Sizemore'],
  },
  {
    id: 17,
    title: 'The Green Mile',
    description: 'Ölüm koridorundaki gardiyanlar, olağanüstü güçlere sahip mahkumla karşılaşır.',
    poster: 'https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
    releaseDate: '1999-12-10',
    rating: 8.6,
    voteCount: 14567,
    genres: [{ id: 9, name: 'Fantastik' }, { id: 7, name: 'Dram' }, { id: 5, name: 'Suç' }],
    runtime: 189,
    director: 'Frank Darabont',
    cast: ['Tom Hanks', 'Michael Clarke Duncan', 'David Morse'],
  },
  {
    id: 18,
    title: 'Spirited Away',
    description: 'Genç kız, ebeveynlerini kurtarmak için ruh dünyasında maceraya atılır.',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg',
    releaseDate: '2001-07-20',
    rating: 8.6,
    voteCount: 13789,
    genres: [{ id: 3, name: 'Animasyon' }, { id: 8, name: 'Aile' }, { id: 9, name: 'Fantastik' }],
    runtime: 125,
    director: 'Hayao Miyazaki',
    cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
  },
]